export const siteConfig = {
  name: 'Aprendizado Acelerado 3.0',
  title: 'Aprendizado Acelerado 3.0 - Carla Brasil',
  description: 'Aprenda mais rápido com técnicas comprovadas de aceleração cognitiva. Descubra como otimizar seu aprendizado com Carla Brasil.',
  url: 'https://aprendizado.acarlabrasil.com.br',
  author: 'Carla Brasil',
  keywords: [
    'Aprendizado Acelerado',
    'Carla Brasil',
    'Técnicas de Estudo',
    'Aceleração Cognitiva',
    'Aprendizagem Eficiente',
    'Metodologia de Estudo',
    'Desenvolvimento Pessoal',
    'Educação',
  ],
  ogImage: {
    url: '/og-image.jpg',
    width: 1200,
    height: 630,
    alt: 'Aprendizado Acelerado 3.0 com Carla Brasil',
  },
  themeColor: '#cc1300',
  locale: 'pt_BR',
} as const;
